name: Build and upload to itch.io Mac

on:
  push:
    branches:
      - master

jobs:
  itchio-deploy:
    runs-on: macos-12

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install libraries
        run: npm i

      - name: Build app
        run: npm run build:mac

      - name: Set up butler
        uses: jdno/setup-butler@v1
        with:
          version: latest

      - name: Push to itch.io
        run: arch -x86_64 butler push release/Unfurl-Mac-Installer.dmg hit-box38/unfurl:mac --token ${{ secrets.ITCH_API_KEY }}
