name: Build and upload to itch.io

on:
  push:
    branches:
      - master

jobs:
  itchio-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      # - name: Build the Docker image
      #   run: docker build -t unfurl:win -f docker/Dockerfile.windows .

      # - name: Run the Docker container to build the app
      #   run: docker run --name unfurl_container unfurl:win

      # - name: Copy artifact from Docker container
      #   run: docker cp unfurl_container:/release/ .

      - name: Install libraries
        run: npm i

      - name: Build app
        run: npm run build:linux

      - name: Deploy
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: linux
          ITCH_GAME: unfurl
          ITCH_USER: hit-box38
          PACKAGE: release/unfurl-Linux.AppImage
